# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 马玉文的博客
email: myw_qd@163.com
description:  技术菜如狗
# baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: 
github_username:  mayuwen

# Build settings
markdown: kramdown
